# version: '3.3'

# volumes:
#   pg_data:
#   static_value:
#   media_value:

# services:

#   db:
#     image: postgres:13.10
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     env_file:
#       - ./.env

#   backend:
#     build: ../foodgram
#     env_file:
#       - ./.env
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ../frontend/:/app/result_build/

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/

# Файл docker-compose.yml

# Версия docker-compose
version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../foodgram/
    env_file:
      - ../.env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: ./
    volumes:
      - static:/staticfiles/
    ports:
      - 8080:80 
